rtl/hqc_accel/hqc_crc16_ccitt.v
rtl/hqc_accel/hqc_sync_fifo.v
rtl/hqc_accel/hqc_security.v
rtl/hqc_accel/hqc_buffer_ram.v
rtl/hqc_accel/hqc_axi4lite_regs.v
rtl/hqc_accel/hqc_spi_slave.v
rtl/hqc_accel/hqc_uart.v
rtl/hqc_accel/hqc_cmd_frame_rx.v
rtl/hqc_accel/hqc_resp_frame_tx.v
rtl/hqc_accel/hqc_pack_engine.v
rtl/hqc_accel/hqc_kem_scheduler.v
rtl/hqc_accel/hqc_rng_sampler_cluster.v
rtl/hqc_accel/hqc_accel_top.v
HQC_weight_sampler&shake_rng_rtl/hqc_keccak_f1600_core.v
HQC_weight_sampler&shake_rng_rtl/hqc_shake_rng.v
HQC_weight_sampler&shake_rng_rtl/hqc_fixed_weight_sampler.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/vector_mul/vector_multi.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/vector_mul/vector_multi_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Encode/RM_encode.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Encode/RS_encode.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Encode/HQC_encode_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/gf_mul/gf_mul_pipline_4.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/gf_mul/gf_mul_pipline_8.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/HQC_decode_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RM_decode/RM_decode_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RM_decode/RM_decode_sum.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RM_decode/RM_HA_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RM_decode/ha_layer.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RM_decode/peak_detect.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RS_decode/RS_decode_top.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RS_decode/RS_syndrome.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RS_decode/RS_ePIMBA.v
HQC_RS_RM_vector(1)/HQC_RS_RM_vector/Decode/RS_decode/RS_error_ca.v
